import type { ComponentStyleMap } from "./types";
import {
  buttonStyleMap,
  iconButtonStyleMap,
  themeSwitchStyleMap,
  iconStyleMap,
  barChartStyleMap,
  chartContainerStyleMap,
  donutChartStyleMap,
  lineChartStyleMap,
  badgeStyleMap,
  emptyStateStyleMap,
  kpiCardStyleMap,
  tableStyleMap,
  alertStyleMap,
  progressStyleMap,
  spinnerStyleMap,
  toastStyleMap,
  checkboxStyleMap,
  fieldStyleMap,
  radioGroupStyleMap,
  selectStyleMap,
  switchStyleMap,
  textInputStyleMap,
  textareaStyleMap,
  containerStyleMap,
  dividerStyleMap,
  gridStyleMap,
  sectionStyleMap,
  stackStyleMap,
  breadcrumbsStyleMap,
  paginationStyleMap,
  sideNavStyleMap,
  tabsStyleMap,
  drawerStyleMap,
  dropdownMenuStyleMap,
  modalStyleMap,
  tooltipStyleMap,
  filterBarPatternStyleMap,
  formSectionPatternStyleMap,
  tableWithToolbarPatternStyleMap,
  headingStyleMap,
  linkStyleMap,
  textStyleMap,
} from "../../components";

export const componentStyleMaps = [
  buttonStyleMap,
  iconButtonStyleMap,
  themeSwitchStyleMap,
  iconStyleMap,
  barChartStyleMap,
  chartContainerStyleMap,
  donutChartStyleMap,
  lineChartStyleMap,
  badgeStyleMap,
  emptyStateStyleMap,
  kpiCardStyleMap,
  tableStyleMap,
  alertStyleMap,
  progressStyleMap,
  spinnerStyleMap,
  toastStyleMap,
  checkboxStyleMap,
  fieldStyleMap,
  radioGroupStyleMap,
  selectStyleMap,
  switchStyleMap,
  textInputStyleMap,
  textareaStyleMap,
  containerStyleMap,
  dividerStyleMap,
  gridStyleMap,
  sectionStyleMap,
  stackStyleMap,
  breadcrumbsStyleMap,
  paginationStyleMap,
  sideNavStyleMap,
  tabsStyleMap,
  drawerStyleMap,
  dropdownMenuStyleMap,
  modalStyleMap,
  tooltipStyleMap,
  filterBarPatternStyleMap,
  formSectionPatternStyleMap,
  tableWithToolbarPatternStyleMap,
  headingStyleMap,
  linkStyleMap,
  textStyleMap,
] as const satisfies readonly ComponentStyleMap[];

export type ComponentStyleMapId = (typeof componentStyleMaps)[number]["id"];

export const getComponentStyleMap = (
  id: ComponentStyleMapId,
): (typeof componentStyleMaps)[number] | undefined =>
  componentStyleMaps.find((styleMap) => styleMap.id === id);
